Create a Pandas DataFrame of shape (5, 4),Fill it with random integers from 10 to 99 using NumPy. Replace all values greater than 50 with NaN.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame(np.random.randint(10,100,size=(5,4)))

In [3]:
df

0   1   2   3
0  40  43  82  11
1  97  30  57  59
2  78  93  62  10
3  97  72  30  98
4  17  53  33  38

In [4]:
df1=df[df<50]

In [5]:
df1

0     1     2     3
0  40.0  43.0   NaN  11.0
1   NaN  30.0   NaN   NaN
2   NaN   NaN   NaN  10.0
3   NaN   NaN  30.0   NaN
4  17.0   NaN  33.0  38.0

Load the "Iris" dataset.Use NumPy to find out how many entries have petal length > 1.5 and sepal width < 3.0.

In [6]:
data = {
    'sepal_length':[5.1,4.9,6.7,5.6,5.8],
    'sepal_width':[3.5,2.8,3.0,2.5,2.6],
    'petal_length':[1.4,1.7,4.4,3.9,1.6],
    'petal_width':[0.2,0.4,1.4,1.3,0.2]
}

In [9]:
df=pd.DataFrame(data)
arr=df.to_numpy()

In [11]:
print(df)
print(arr)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          2.8           1.7          0.4
2           6.7          3.0           4.4          1.4
3           5.6          2.5           3.9          1.3
4           5.8          2.6           1.6          0.2
[[5.1 3.5 1.4 0.2]
 [4.9 2.8 1.7 0.4]
 [6.7 3.  4.4 1.4]
 [5.6 2.5 3.9 1.3]
 [5.8 2.6 1.6 0.2]]


In [13]:
mask = (df["petal_length"].values > 1.5) & (df["sepal_width"].values < 3.0)
np.sum(mask)

3

Generate a NumPy array of shape (6, 3) from a normal distribution. Add this array as new columns "col_A", "col_B", "col_C" to an empty DataFrame.

In [18]:
normal_array=np.random.randn(6, 3)
new_df=pd.DataFrame()
new_df[['col_A','col_B','col_C']]=normal_array
print(new_df)

      col_A     col_B     col_C
0 -0.270867 -0.728189  0.401367
1 -0.560520  0.026303  0.103725
2 -1.603880 -1.690843 -1.844806
3 -0.174218  0.564413 -0.400879
4  0.575409  0.538586  0.277586
5 -0.436742 -0.600538  0.743374


create a NumPy array of shape (4, 4),Use broadcasting to subtract the mean of each column from the respective column, and insert the result into a new DataFrame.

In [20]:
matrix=np.random.randint(1,10,size=(4,4))
col_means=matrix.mean(axis=0)
centered_matrix=matrix-col_means
centered_df= pd.DataFrame(centered_matrix,columns=['A','B','C','D'])

In [21]:
print(centered_df)

     A     B    C     D
0  1.5  1.25 -0.5 -0.25
1  0.5 -0.75  4.5  0.75
2  1.5 -1.75 -1.5 -3.25
3 -3.5  1.25 -2.5  2.75


Create a DataFrame with columns "A" and "B" of size 6, Use NumPy to calculate the row-wise maximum and add it as a column "Max_Val"

In [22]:
df = pd.DataFrame(np.random.randn(6, 2), columns=['A', 'B'])
df['Max_Val'] = np.maximum(df['A'], df['B'])

print(df)
print(df)

          A         B   Max_Val
0  0.833936 -0.930386  0.833936
1  0.289130 -0.001986  0.289130
2 -0.104988  0.288903  0.288903
3 -1.752557 -1.956498 -1.752557
4 -1.649663  0.319895  0.319895
5  1.110477 -0.225138  1.110477
          A         B   Max_Val
0  0.833936 -0.930386  0.833936
1  0.289130 -0.001986  0.289130
2 -0.104988  0.288903  0.288903
3 -1.752557 -1.956498 -1.752557
4 -1.649663  0.319895  0.319895
5  1.110477 -0.225138  1.110477
