In [1]:
import numpy as np

In [2]:
#Create a numpy array

a = np.array([10,40,50,60])
print(a)

[10 40 50 60]


In [3]:
#2d array

a = np.array([[5,6],[7,8]])
print(a)

[[5 6]
 [7 8]]


In [5]:
#3d array

a = np.array([[[5,6],[7,8]],[[10,12],[25,30]]])
print(a)

[[[ 5  6]
  [ 7  8]]

 [[10 12]
  [25 30]]]


In [6]:
#Special arrays

np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.diag([1,2,3,5,6,7])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 7]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [15]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.linspace(10,50,8)

array([10.        , 15.71428571, 21.42857143, 27.14285714, 32.85714286,
       38.57142857, 44.28571429, 50.        ])

In [17]:
#Rank/shape of the matrix

a = np.array([[3,4],[30,40]])

In [19]:
a.shape #rank of the matrix

(2, 2)

In [20]:
print(a)

[[ 3  4]
 [30 40]]


In [21]:
a.ndim #number of dimensions

2

In [22]:
a = np.array([[[5,6],[7,8]],[[10,12],[25,30]]])
a.ndim

3

In [ ]:
a.size #no. of elements in the matrix

8

In [24]:
a.dtype #return the data type of the matrix

dtype('int32')

In [27]:
#why it is better than lists in the calculation of mathematical functions

import time

lst = list(range(1000000))
start_pt = time.time()
lst2 = [2*item for item in lst]
print(f"time taken using the list: {round(time.time()-start_pt,3)} seconds")

time taken using the list: 0.258 seconds


In [28]:
arr = np.arange(1000000)
start_pt = time.time()
arr2 = arr*2
print(f"time taken using the numpy array: {round(time.time()-start_pt,3)} seconds")

time taken using the numpy array: 0.002 seconds


In [1]:
import numpy as np

In [2]:
arr = np.array([23,34,56,67,89,-76,54,21,0])
print(arr)

[ 23  34  56  67  89 -76  54  21   0]


In [3]:
arr[2]

56

In [4]:
arr[-5]

89

In [5]:
arr[2:6]

array([ 56,  67,  89, -76])

In [6]:
arr[-8:-3]

array([ 34,  56,  67,  89, -76])

In [9]:
arr = np.array([[23,1,-5,4,34,1],[12,23,5,6,0,3],[9,8,7,6,5,32],[1,-1,-34,12,2,7]])
print(arr)

[[ 23   1  -5   4  34   1]
 [ 12  23   5   6   0   3]
 [  9   8   7   6   5  32]
 [  1  -1 -34  12   2   7]]


In [10]:
arr[2,3]

6

In [11]:
arr[1,5]

3

In [12]:
arr[3:]

array([[  1,  -1, -34,  12,   2,   7]])

In [15]:
arr[:,2]

array([ -5,   5,   7, -34])

In [16]:
arr[:,3]

array([ 4,  6,  6, 12])

In [17]:
arr[1:,3]

array([ 6,  6, 12])

In [18]:
arr = np.array([23,34,56,67,89,-76,54,21,0])
print(arr)

[ 23  34  56  67  89 -76  54  21   0]


In [ ]:
arr>10 #boolean indexing

array([ True,  True,  True,  True,  True, False,  True,  True, False])

In [20]:
arr==15

array([False, False, False, False, False, False, False, False, False])

In [21]:
arr[arr>10]

array([23, 34, 56, 67, 89, 54, 21])

In [ ]:
arr[arr<0] #View

array([-76])

In [ ]:
#Arthematic Operations

arr+2 #[ 23  34  56  67  89 -76  54  21   0]

array([ 25,  36,  58,  69,  91, -74,  56,  23,   2])

In [24]:
arr*10

array([ 230,  340,  560,  670,  890, -760,  540,  210,    0])

In [25]:
arr/5

array([  4.6,   6.8,  11.2,  13.4,  17.8, -15.2,  10.8,   4.2,   0. ])

In [26]:
arr**3

array([  12167,   39304,  175616,  300763,  704969, -438976,  157464,
          9261,       0], dtype=int32)

In [27]:
#mathematical operations

arr = np.array([34,12,4,5,89,2,76])

np.sqrt(arr)

array([5.83095189, 3.46410162, 2.        , 2.23606798, 9.43398113,
       1.41421356, 8.71779789])

In [28]:
np.exp(arr)

array([5.83461743e+14, 1.62754791e+05, 5.45981500e+01, 1.48413159e+02,
       4.48961282e+38, 7.38905610e+00, 1.01480039e+33])

In [30]:
arr = np.array([34,-90,21,34,-76])
np.abs(arr)

array([34, 90, 21, 34, 76])

In [31]:
#Broadcasting

arr1 = np.array([[23,54,67],[1,5,7],[0,9,8]])
arr2 = np.array([40,50,70])

In [57]:
arr1

array([[23, 54, 67],
       [ 1,  5,  7],
       [ 0,  9,  8]])

In [58]:
arr1.T

array([[23,  1,  0],
       [54,  5,  9],
       [67,  7,  8]])

In [59]:
arr2

array([40, 50, 70])

In [60]:
arr2.T

array([40, 50, 70])

In [32]:
arr1.shape

(3, 3)

In [44]:
arr2.shape

(3,)

In [45]:
b = arr2.reshape(1,3)

In [46]:
b.shape

(1, 3)

In [43]:
arr2.reshape(1,3).ndim

2

In [34]:
arr1+arr2

array([[ 63, 104, 137],
       [ 41,  55,  77],
       [ 40,  59,  78]])

In [47]:
arr1+b

array([[ 63, 104, 137],
       [ 41,  55,  77],
       [ 40,  59,  78]])

In [48]:
a = np.array([1,3,4,6,78,2,65,678,8,32,5667,1,0,434,5,1,667,343])
a.size

18

In [49]:
a.ndim

1

In [50]:
b = a.reshape(2,9)
print(b)

[[   1    3    4    6   78    2   65  678    8]
 [  32 5667    1    0  434    5    1  667  343]]


In [52]:
c = a.reshape(3,6)
print(c)

[[   1    3    4    6   78    2]
 [  65  678    8   32 5667    1]
 [   0  434    5    1  667  343]]


In [54]:
d = a.reshape(6,3)
print(d)

[[   1    3    4]
 [   6   78    2]
 [  65  678    8]
 [  32 5667    1]
 [   0  434    5]
 [   1  667  343]]


In [ ]:
e = a.reshape(2,3,3) #view
print(e)

[[[   1    3    4]
  [   6   78    2]
  [  65  678    8]]

 [[  32 5667    1]
  [   0  434    5]
  [   1  667  343]]]


In [56]:
e.ndim

3

In [1]:
import numpy as np

In [4]:
a = np.array([2,4,6,89,9,1,2,23,65,2,90,8])
print(a)

[ 2  4  6 89  9  1  2 23 65  2 90  8]


In [5]:
b = a.reshape(3,4)
print(b)

[[ 2  4  6 89]
 [ 9  1  2 23]
 [65  2 90  8]]


In [6]:
a[2] = 300

In [7]:
print(a)

[  2   4 300  89   9   1   2  23  65   2  90   8]


In [8]:
print(b)

[[  2   4 300  89]
 [  9   1   2  23]
 [ 65   2  90   8]]


In [14]:
a.resize(3,4)
c = a
print(c)

[[  2   4 300  89]
 [  9   1   2  23]
 [ 65   2  90   8]]


In [16]:
arr = np.array([1,2,3,5,6,7,89,9,10,11,12,13])
print(arr)

[ 1  2  3  5  6  7 89  9 10 11 12 13]


In [ ]:
arr_resized = np.resize(arr,(3,4))
print(arr_resized)

[[ 1  2  3  5]
 [ 6  7 89  9]
 [10 11 12 13]]


In [19]:
arr[2] = 1000
print(arr)

[   1    2 1000    5    6    7   89    9   10   11   12   13]


In [20]:
print(arr_resized)

[[ 1  2  3  5]
 [ 6  7 89  9]
 [10 11 12 13]]


In [21]:
arr_1 = np.array([[1,2,3,4],[5,6,7,8],[90,100,110,120],[-1,-2,-3,-4]])
print(arr_1)

[[  1   2   3   4]
 [  5   6   7   8]
 [ 90 100 110 120]
 [ -1  -2  -3  -4]]


In [22]:
print(arr_1.shape)

(4, 4)


In [23]:
arr_1_ravel = arr_1.ravel()
print(arr_1_ravel)

[  1   2   3   4   5   6   7   8  90 100 110 120  -1  -2  -3  -4]


In [24]:
arr_1_ravel.shape

(16,)

In [25]:
arr_1[2,3] = 3000
print(arr_1)

[[   1    2    3    4]
 [   5    6    7    8]
 [  90  100  110 3000]
 [  -1   -2   -3   -4]]


In [26]:
print(arr_1_ravel)

[   1    2    3    4    5    6    7    8   90  100  110 3000   -1   -2
   -3   -4]


In [27]:
arr_1_flatten = arr_1.flatten()
print(arr_1_flatten)

[   1    2    3    4    5    6    7    8   90  100  110 3000   -1   -2
   -3   -4]


In [28]:
arr_1[1,2] = 908
print(arr_1)

[[   1    2    3    4]
 [   5    6  908    8]
 [  90  100  110 3000]
 [  -1   -2   -3   -4]]


In [29]:
print(arr_1_flatten)

[   1    2    3    4    5    6    7    8   90  100  110 3000   -1   -2
   -3   -4]


reshape - changes the shape of the matrix and creates a view
resize - changes the shape of the matrix and createds a copy

ravel - flatten the array and creates a view
flatten - flattens the array and creates a copy

In [30]:
#Vertical and horizontal stacks

a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [31]:
a.shape

(2, 2)

In [32]:
b.shape

(2,)

In [ ]:
np.vstack((a,b)) #the number of columns in both the matrix should be same

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a,b.reshape(2,1))) #the number of rows in both the matrix should be same

array([[1, 2, 5],
       [3, 4, 6]])

In [40]:
print(a)

[[1 2]
 [3 4]]


In [42]:
print(b.shape)

(2,)


In [44]:
b.reshape(1,2).shape

(1, 2)

In [ ]:
#concatenate

np.concatenate((a,b.reshape(1,2)),axis=0) #vstack or row wise concatenation

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.reshape(2,1)),axis=1) #hstack or column wise concatenation

array([[1, 2, 5],
       [3, 4, 6]])

In [47]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.hsplit(x,2) #to split the columnwise arrays

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(x,2) #to split the rowwise arrays

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
#statistical functions

#mean, median, std-dev, percentiles

arr = np.array([10,19,18,17,16,15,14])
np.mean(arr)

15.571428571428571

In [52]:
np.median(arr)

16.0

In [53]:
np.std(arr)

2.770102775666474

In [55]:
np.percentile(arr,[10,20,50,90,99.9])

array([12.4  , 14.2  , 16.   , 18.4  , 18.994])

In [56]:
arr = np.array([[2,3,4,65],[12,23,45,67],[10,19,18,17]])
print(arr)

[[ 2  3  4 65]
 [12 23 45 67]
 [10 19 18 17]]


In [ ]:
np.mean(arr,axis=0) #it creates horizontal means

array([ 8.        , 15.        , 22.33333333, 49.66666667])

In [ ]:
np.mean(arr,axis=1) #it creates vertical means

array([18.5 , 36.75, 16.  ])

In [1]:
import numpy as np

In [2]:
#Element wise math operations

a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [3]:
#Finding square roots of all the elements

np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [ ]:
np.log(a) #Finding the logirthm values

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [ ]:
np.exp(a) #finding the exponential values

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [ ]:
np.sin(a) #angles in the radians

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

1 radian  -> 180/pi()
1 degrees -> pi()/180


In [8]:
#conversion of 20 radians to degrees
import math

20*180/math.pi

1145.9155902616465

In [9]:
10*math.pi/180

0.17453292519943295

In [10]:
#Aggregation functions

a= np.array([[12,45,76,90],[9,2,4,6],[-5,-4,23,67]])
a

array([[12, 45, 76, 90],
       [ 9,  2,  4,  6],
       [-5, -4, 23, 67]])

In [11]:
a.shape

(3, 4)

In [12]:
np.sum(a)

325

In [13]:
np.sum(a,axis=0)

array([ 16,  43, 103, 163])

In [14]:
np.sum(a,axis=1)

array([223,  21,  81])

In [16]:
np.min(a)

-5

In [17]:
np.min(a,axis=0)

array([-5, -4,  4,  6])

In [18]:
np.min(a,axis=1)

array([12,  2, -5])

In [19]:
np.max(a)

90

In [20]:
np.max(a,axis=0), np.max(a,axis=1)

(array([12, 45, 76, 90]), array([90,  9, 67]))

In [21]:
#Statistical terms: std-dev and variance

np.std(a)

32.19590639955472

In [22]:
np.std(a,axis=0),np.std(a,axis=1)

(array([ 7.40870359, 21.8225164 , 30.46673961, 35.44322534]),
 array([30.05307805,  2.58602011, 29.23503891]))

In [23]:
np.var(a)

1036.576388888889

In [24]:
np.var(a,axis=0), np.var(a,axis=1)

(array([  54.88888889,  476.22222222,  928.22222222, 1256.22222222]),
 array([903.1875,   6.6875, 854.6875]))

In [25]:
#comparison and logical functions

np.greater(a,10)

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False,  True,  True]])

In [26]:
np.equal(a,23)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [27]:
np.logical_and(a>0,a==10)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
np.logical_or(a>0,a==10)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True]])

In [ ]:
#random number genearation

np.random.rand(5) #Float values between 0 to 1

array([0.89243775, 0.36614868, 0.18206907, 0.43253413, 0.60874182])

In [ ]:
np.random.randn(10) #Float values between 0 to 1 and which follows standard normal distribution

array([ 0.97209143, -0.28035972, -1.14216315, -1.96609146,  1.4785002 ,
        1.00609203, -1.27483874,  0.38707156, -0.35432443, -0.233623  ])

In [ ]:
np.random.randint(10,20,size=(2,2)) #int values with desired size/shape

array([[11, 18],
       [17, 11]])

In [ ]:
np.random.choice(10,5) #int values from 0 to the number(10)

array([1, 7, 8, 5, 3])

In [ ]:
np.random.choice([10,34,65,78,9,0,12,4,100,40,6,7],10) #int values based on the size(10) from the given list of items

array([65,  0,  4,  4,  0, 10,  6,  9,  4,  4])

In [105]:
#linear algebra functions

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [106]:
a

array([[1, 2],
       [3, 4]])

In [107]:
b

array([[5, 6],
       [7, 8]])

In [108]:
#dot product

np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [109]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [110]:
np.dot(b,b)

array([[ 67,  78],
       [ 91, 106]])

In [ ]:
a@b #dot product between the arrays

array([[19, 22],
       [43, 50]])

In [112]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(a) #determinant of the matrix A

-2.0000000000000004

In [114]:
np.linalg.det(b)

-2.000000000000005

In [115]:
np.linalg.matrix_rank(a)

2

In [ ]:
a = np.array([[10,20],[30,40]])
b = np.array([2,3])

In [116]:
np.linalg.solve(a,b)

array([[-3., -4.],
       [ 4.,  5.]])

In [117]:
#Calculation of eigen values and eigen vectors

a = np.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [118]:
np.linalg.eig(a)

EigResult(eigenvalues=array([ 1.61168440e+02, -1.11684397e+01,  2.06802688e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [ ]:
3x + y+ 2z = 13
x + 2y+ 3z = 14
4x + 5y -z  = 21

In [121]:
a = np.array([[3,1,2],[1,2,3],[4,5,-1]])
b = np.array([13,14,21])

In [122]:
np.linalg.solve(a,b)

array([2., 3., 2.])

In [1]:
import numpy as np

In [3]:
a = np.array([23,34,56,678,1,4,8,9,0,56,9,0])
a[[1,5,8]]

array([34,  4,  0])

In [4]:
a[[-1,-5,-8]]

array([0, 9, 1])

In [5]:
a = np.array([[12,34,56],[4,87,23],[0,9,8],[23,45,67]])

In [6]:
a

array([[12, 34, 56],
       [ 4, 87, 23],
       [ 0,  9,  8],
       [23, 45, 67]])

In [10]:
rows = [1,2,3]
cols = [0,2,1]

In [11]:
a[rows,cols]

array([ 4,  8, 45])

In [ ]:
#Fancy/Boolean indexing - this will be used to filter the elements in the numpy array based on a condition

a = np.array([90,34,-9,-4,3,-45,32,1,0,6,-78,-230])
mask = a<0

In [17]:
a[mask]

array([  -9,   -4,  -45,  -78, -230])

In [18]:
a = np.array([[12,34,56],[4,87,23],[0,9,8],[23,45,67]])

mask  = a>10
a[mask]

array([12, 34, 56, 87, 23, 23, 45, 67])

In [19]:
#Conditional search
#Replace all the positive numbers with "Positive" and replace all the negative numbers with "Negative"

a = np.array([90,34,-9,-4,3,-45,32,1,0,6,-78,-230])

#Syntax: np.where(condition,pass_value,fail_value)

np.where(a>0,"Positive","Negative")

array(['Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Negative'], dtype='<U8')

In [20]:
#Replae all even numbers with 0 otherwise replae with 1
a = np.array([[12,34,56],[4,87,23],[0,9,8],[23,45,67]])

np.where(a%2==0,0,1)

array([[0, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [22]:
#If you have multiple conditions then we can use np.select

#syntax: np.select(conditions,choices)

marks = np.array([23,45,67,89,90,32,54,14,90,9,32,45,87,100,23,67,62,94,21])

conditions = [marks>=60,
(marks>=40) & (marks<60),
marks<40]

choices = ["First","Second","Third"]

np.select(conditions,choices)

array(['Third', 'Second', 'First', 'First', 'First', 'Third', 'Second',
       'Third', 'First', 'Third', 'Third', 'Second', 'First', 'First',
       'Third', 'First', 'First', 'First', 'Third'], dtype='<U6')

In [ ]:
np.unique(marks) #This will give you the unique items innthe ascending order

array([  9,  14,  21,  23,  32,  45,  54,  62,  67,  87,  89,  90,  94,
       100])

In [ ]:
#Sorting

np.sort(marks) #ascending order

array([  9,  14,  21,  23,  23,  32,  32,  45,  45,  54,  62,  67,  67,
        87,  89,  90,  90,  94, 100])

In [ ]:
np.sort(marks)[::-1] #desending order

array([100,  94,  90,  90,  89,  87,  67,  67,  62,  54,  45,  45,  32,
        32,  23,  23,  21,  14,   9])

In [28]:
np.sort(marks)[::-4]

array([100,  89,  62,  32,  21])

In [29]:
#sorting the items row wise and column wise in the fiven array

a = np.array([[12,34,56],[4,87,23],[0,9,8],[23,45,67]])
a

array([[12, 34, 56],
       [ 4, 87, 23],
       [ 0,  9,  8],
       [23, 45, 67]])

In [32]:
np.sort(a,axis=0)

array([[ 0,  9,  8],
       [ 4, 34, 23],
       [12, 45, 56],
       [23, 87, 67]])

In [33]:
np.sort(a,axis=1)

array([[12, 34, 56],
       [ 4, 23, 87],
       [ 0,  8,  9],
       [23, 45, 67]])

In [ ]:
#arg sort  - will return the indices of the sorted numpy array

marks = np.array([23,45,67,89,90,32,54,14,90,9,32,45,87,100,23,67,62,94,21])

In [34]:
np.sort(marks)

array([  9,  14,  21,  23,  23,  32,  32,  45,  45,  54,  62,  67,  67,
        87,  89,  90,  90,  94, 100])

In [ ]:
np.argsort(marks) #this returns the indices of the ascending order items 

array([ 9,  7, 18, 14,  0,  5, 10,  1, 11,  6, 16, 15,  2, 12,  3,  4,  8,
       17, 13], dtype=int64)

In [36]:
np.argsort(marks)[::-1] #this will return the indices of the descending order items

array([13, 17,  8,  4,  3, 12,  2, 15, 16,  6, 11,  1, 10,  5,  0, 14, 18,
        7,  9], dtype=int64)

In [37]:
#argmax -> will return the index position of the maximum value of the array

np.argmax(marks)

13

In [38]:
#argmin -> will return the index position of the minimum value of the array

np.argmin(marks)

9

In [39]:
#np.clip -> adjust the array with in the given range

marks = np.array([23,45,67,89,90,32,54,14,90,9,32,45,87,100,23,67,62,94,21])

#syntax: np.clip(array_name,min,max)

np.clip(marks,40,80)

array([40, 45, 67, 80, 80, 40, 54, 40, 80, 40, 40, 45, 80, 80, 40, 67, 62,
       80, 40])